# Site settings
baseurl = "http://blog.ravitezu.me" #without ending slash
languageCode = "en-us"
theme = "ghostwriter"
title = "RaviTezu | Blog"
copyright = "Ravi Teja Pothana"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-84283793-1"
disqusShortname = "blog-ravitezu-me"

[Author]
    name = "My Name"
    profile = "https://twitter/ravitezu"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "RaviTezu Learn👓- Share"
    description = "Engineer • Hacker • Optimist • Runner • Gopher"
    github = "https://github.com/ravitezu"
    linkedin = "http://in.linkedin.com/pub/raviteja-pothana/46/772/354"
    twitter = "https://twitter.com/RaviTezu"
    stackoverflow = "http://stackoverflow.com/users/1280320/ravitezu"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
